[package]
name = "lst"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hifitime = "2"
chrono = "0.4"
divrem = "1.0.0"